
function init(self)
	msg.post("/model", "load_mesh", {path = "/models/dancer.bin"})
	
	msg.post(".", "acquire_input_focus")

	self.light = vmath.vector4(0, 0, 8, 0)
	msg.post("@render:", "clear_color", {color = vmath.vector4(.5, 0.5,0.5, 1)})
	
	self.touch_down = false
	self.count = 1
	self.time = 0
end

function update(self, dt)
	if self.loaded then
		self.time = self.time + dt
		if self.time > .03 then
			self.time = 0.0
			msg.post("/model", "set_frame", {frame = self.count})
			if self.count > self.total_frames then
				self.count = 1
			else
				self.count = self.count + 1
			end
		end
		
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("meshes_loaded") then
		pprint("Success!")
		self.total_frames = message.frames
		self.loaded = true
	end
end

function on_input(self, action_id, action)
	
	if action_id == hash("touch") then
		self.touch_down = true
		if action.released then
			self.touch_down = false
		end
	end

	if self.touch_down and action_id == nil then
		go.set(".", "euler.y", go.get(".", "euler.y") + action.dx * 0.5)
		go.set(".", "euler.x", go.get(".", "euler.x") - action.dy * 0.5)
	end
end
