
function init(self)

	msg.post("/model", "load_mesh", {path = "/blender/sample.bin"})
	
	msg.post(".", "acquire_input_focus")

	self.light = vmath.vector4(0, 0, 8, 0)
	msg.post("@render:", "clear_color", {color = vmath.vector4(.5, 0.5,0.5, 1)})
	
	self.touch_down = false

end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	
	if action_id == hash("touch") then
		self.touch_down = true
		if action.released then
			self.touch_down = false
		end
	end

	if self.touch_down and action_id == nil then
		go.set(".", "euler.y", go.get(".", "euler.y") + action.dx * 0.5)
		go.set(".", "euler.x", go.get(".", "euler.x") - action.dy * 0.5)
	end
end
